app:
    resource: '@AppBundle/Controller/'
    type: annotation 

blog_list:
    path:      /blog/{page}
    defaults:  { _controller: AppBundle:Blog:list, page: 1 }
    requirements:
        page: '\d+'

blog_show:
    path:     /blog/{slug}
    defaults: { _controller: AppBundle:Blog:show }

prueba_show:
    path:     /prueba/{slug}
    defaults: { _controller: AppBundle:Prueba:show }

article_show:
  path:     /articles/{_locale}/{year}/{slug}.{_format}
  defaults: { _controller: AppBundle:Article:show, _format: html }
  requirements:
      _locale:  en|fr
      _format:  html|rss
      year:     \d+

empresa_mostrarAll:
    path:      /empresas
    defaults:  { _controller: AppBundle:Empresa:listarTodas}

empresa_mostrarUna:
    path:      /empresa/{id}
    defaults:  { _controller: AppBundle:Empresa:listarUna, id: 1 }    
    requirements:
        id: '\d+'   

empresa_nombreEmpresa:
    path:      /nombre
    defaults:  { _controller: AppBundle:Empresa:nombreEmpresa}        

mensaje:
    path:     /mensaje/{men}
    defaults: { _controller: AppBundle:Empresa:mensaje, men: '' }    

contactar:
    path:     /contactar/{marca}
    defaults: { _controller: AppBundle:Empresa:contactar, marca: 'nike' }   

contactarAdidasss:
    path:     /contactarAdidas
    defaults: { _controller: AppBundle:Empresa:contactarAdidas}        

empresa_crear:
    path:      /crear_empresa
    defaults:  { _controller: AppBundle:Empresa:crearEmpresa}      

empresa_buscar:
    path:      /buscar_empresa/{id}
    defaults:  { _controller: AppBundle:Empresa:buscarEmpresa, id: 1}  

empresa_buscarNombre:
    path:      /buscar_empresa_nombre/{nombre}
    defaults:  { _controller: AppBundle:Empresa:buscarEmpresaPorNombre, nombre: 'assics'}        

empresa_crearEmpFormulario:
    path:      /form_crear
    defaults:  { _controller: AppBundle:Empresa:crearEmpresaFormulario }    

empresa_recuperarValoresFormulario:
    path:      /crear_empresa_form
    defaults:  { _controller: AppBundle:Empresa:recuperarValoresFormulario } 


            